<script setup lang="ts">
</script>

<template>
    <div>Admin page</div>

    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
    <div>Admin page</div>
</template>
