services:
  # PostgreSQL Database Service
  db:
    image: postgres:16-alpine
    container_name: project-loved-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-project-loved}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  # Rust Backend Service
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: project-loved-backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB:-project-loved}
      - APP_ENVIRONMENT=${APP_ENVIRONMENT:-development}
      - SERVER_PORT=${SERVER_PORT:-3000}
      - SERVER_SECRET=${SERVER_SECRET}
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - cargo-target:/app/target
    env_file:
      - .env

volumes:
  postgres-data:
  cargo-target:
  node-modules: