[package]
name = "athena_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full"] } # I just don't really like 2.x's breaking changes.
quote = "1.0"