[package]
name = "queue_processor"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.0", features = ["full"] }
redis = { version = "0.29.1", features = ["tokio-comp"] }
dotenvy = "0.15.0"
async-trait = "0.1.87"
tokio-cron-scheduler = "0.6"