name: Lint checker
on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install -g eslint jiti
      - run: bun install

      - run: eslint .
        working-directory: ./packages/${{ matrix.dir }}
    strategy:
      matrix:
        dir: [api, loved, permissions, ui, website]
